// Code generated by tools/schema-gen.py; DO NOT EDIT.
package protocol

import (
	"encoding/json"
	"time"
)

type Envelope struct {
	Zero           string          `json:"zero"`
	Type           string          `json:"type"`
	ID             string          `json:"id"`
	Time           time.Time       `json:"time"`
	Source         string          `json:"source"`
	Target         string          `json:"target,omitempty"`
	CorrelationID  string          `json:"correlation_id,omitempty"`
	CausationID    string          `json:"causation_id,omitempty"`
	TraceID        string          `json:"trace_id,omitempty"`
	TTL            int64           `json:"ttl_ms,omitempty"`
	Classification string          `json:"classification,omitempty"`
	Body           json.RawMessage `json:"body"`
}

var messageTypes = map[string]bool{
	"session.hello":        true,
	"session.welcome":      true,
	"node.register":        true,
	"node.heartbeat":       true,
	"capability.advertise": true,
	"capability.invoke":    true,
	"capability.accepted":  true,
	"capability.result":    true,
	"event.publish":        true,
	"state.result":         true,
	"sync.request":         true,
	"ack":                  true,
	"session.error":        true,
	"display.telemetry":    true,
}
