#!/usr/bin/env python3
"""Generate language bindings from the single release manifest; --check never writes."""
import json,sys
from pathlib import Path
root=Path(__file__).resolve().parents[1]
m=json.loads((root/'core/release/manifest.json').read_text())
outputs={root/'nodes/esp32-desk/main/zero_release.h':f'// Generated by tools/release-gen.py\n#define ZERO_VERSION "{m["version"]}"\n#define ZERO_BUILD "{m["build"]}"\n',root/'apps/macos/Sources/ZeroKit/Release.swift':f'// Generated by tools/release-gen.py\npublic enum ZeroRelease {{ public static let version = "{m["version"]}"; public static let build = "{m["build"]}" }}\n'}
for p,s in outputs.items():
 if '--check' in sys.argv:
  if not p.exists() or p.read_text()!=s:sys.exit(f'Stale release binding: {p}')
 else:p.write_text(s)
