#!/usr/bin/env python3
"""Generate the diagnostic envelope and message registry from canonical JSON Schema."""
import json
from pathlib import Path
import subprocess
root=Path(__file__).resolve().parents[1]
schema=json.loads((root/"proto/schemas/envelope.json").read_text())
names={"zero":"Zero","type":"Type","id":"ID","time":"Time","source":"Source","target":"Target",
       "correlation_id":"CorrelationID","causation_id":"CausationID","trace_id":"TraceID","ttl_ms":"TTL",
       "classification":"Classification","body":"Body"}
lines=['// Code generated by tools/schema-gen.py; DO NOT EDIT.','package protocol',
       'import("encoding/json";"time")','type Envelope struct {']
for field,prop in schema["properties"].items():
    typ="string"
    if prop.get("format")=="date-time":typ="time.Time"
    elif prop.get("type")=="integer":typ="int64"
    elif prop.get("type")=="object":typ="json.RawMessage"
    optional="" if field in schema["required"] else ",omitempty"
    lines.append(f'{names[field]} {typ} `json:"{field}{optional}"`')
lines.extend(['}','var messageTypes = map[string]bool{'])
for kind in schema["properties"]["type"]["enum"]:lines.append(json.dumps(kind)+':true,')
lines.append('}')
target=root/"core/protocol/models_generated.go"
target.write_text('\n'.join(lines)+'\n')
subprocess.run(['gofmt','-w',str(target)],check=True)
